### ISSUE TITLE
Filtering outliers

### ISSUE THREAD

**Issue by ArkfrostLumas** [DeltaBreaker/Lolorito#5]
Hey there!

I find this app to be amazing. However there is one issue I have:
When sorting by crafting cost the top results are always crazy outliers from people transferring gil via the market board. Stuff like a hempen shirt that costs like 50 gil to craft selling for 50 million gil or something. It would be cool to have an option to filter outliers, so when you select crafting cost and there's a result that is over 1000% higher than the average selling price, then these results get filtered out.

Cheers :)

**Comment by DeltaBreaker** [comment]
That's an issue I've thought on for a bit, but haven't found a good way to solve yet. I've tried a few methods but none worked in the way I would have hoped. When there's a lot of sales to compare against its pretty obvious, but for items that have just one or a couple sales its much harder to determine. If one item has one sale for 5mil there's no way to tell if that was an outlier or not by that one listing alone. On the other end, when people sell items for way less than the normal price that could flag normally listed sales as outliers if there's only a few sales to look at. In the end I decided to let human discretion decide what is what instead of potentially removing honest data, but ill keep the issue open and keep thinking about better solutions! Maybe the best thing would just be to sacrifice the accuracy of low sale items for sake the more popular ones.

Thanks for the feedback! c:

**Comment by ArkfrostLumas** [comment]
I think starting from 5 items or so it would already help a lot by first checking the median price instead of average, and then removing all sales that sold for 10x the median price or half of it if it's an item that typically sells for more than 9999 gil, for items between 999 and 9999 gil for 15x or an eight of it, and for items below that all items that sold for 20x the median or on tenth. 

So if an item sold for 1, 50, 60, 250 and 2000 gil, then all items above 1200 and below 6 gil don't get counted. If it sold for 200, 500, 5000, 76000 and 80.000 all items above 75000 and below 333 get removed, and if something sold for 30000. 55000, 80000, 81000 and 1 million, all items above 800.000 and below 40000 get removed.

Also, all items yields over a settable amount multiple of its crafting cost (like 5x its crafting cost) they get removed from the calculation in the 'crafting' column.

The more items are sold, the more accurate this becomes automatically.

Those as options you can check or uncheck would already help massively.

**Comment by DeltaBreaker** [comment]
I took your advice and implemented a form of outlier removal for items with >5 sales. This combined with filtering unsold items seems to mostly solve the issue, at least for results sorting by crafting profit. I'll keep listening to feedback about the topic and try and implement even better solutions as I find them in the future. Thank you for the support!
